[package]
name = "mcp_server_notion"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[lib]
path = "src/notion_mcp.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.7.0"
serde = "1.0"
schemars = "0.8"
